controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\EntryForm;
use app\models\RegisterForm;
use app\models\UpdateForm;
use app\models\Users;
use app\models\UsersInfo;
use app\models\Roles;
use yii\helpers\Json;

use yii\web\UploadedFile;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->pass = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    // public function actionContact()
    // {
    //     $model = new ContactForm();
    //     if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
    //         Yii::$app->session->setFlash('contactFormSubmitted');

    //         return $this->refresh();
    //     }
    //     return $this->render('contact', [
    //         'model' => $model,
    //     ]);
    // }

    /**
     * Displays about page.
     *
     * @return string
     */
    // public function actionAbout()
    // {
    //     return $this->render('about');
    // }

    // public function actionSay($message = 'Hello')
    // {
    //     return $this->render('say', ['message' => $message]);
    // }

    public function actionEntry()
    {
        $msg='ok';
        $model = new EntryForm();
        

        if ($model->load(Yii::$app->request->post())) {
            
            $model->image = UploadedFile::getInstance($model, 'image');
            $nimage = UploadedFile::getInstance($model, 'image');
            
            if ($model->upload()) {
                $usr = Users::findOne($model->user_id);
                // file is validated
                $usr->img_src = $nimage->basename. '.' . $nimage->extension;
                $path = Yii::$app->basePath . '/web/images/'. $nimage->baseName . '.' . $nimage->extension;
                //$nimage->saveAs(Yii::$app->basePath . $this->image->baseName . '.' . $this->image->extension);
                // $nimage->saveAs($path);
                if($nimage->extension=="jpg"){
                    // var_dump($nimage->extension);
                    $path = Yii::$app->basePath . '/web/images/jpg/'. $nimage->baseName . '.' . $nimage->extension;;
                    $nimage->saveAs($path);
                }
                
                // var_dump($nimage->extension);die();
                $usr->save();
                return $this->render('entry-confirm', ['msg' => $msg]);
            }
        }else return $this->render('entry', ['model' => $model,]);




        // return $this->render('upload', ['model' => $model]);

        // if ($model->load(Yii::$app->request->post()) ) 
        // {
            
        //     $usr = Users::findOne($model->user_id);
        //     $image = UploadedFile::getInstance($model, 'image');
        //     $usr->img_src = $image->name;
        //     $usr->save();

        //      if (!is_null($image)) 
        //     {
                
               
        //        $model->img_src = $image->name;
              
        //        $ext = end((explode(".", $image->name)));
        //        Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/images/';
        //        print_r($model->getErrors());die;

        //         if($ext=='jpg'){
        //             $path = Yii::$app->params['uploadPath'] .'/jpg/'. $image->name;
        //             $image->saveAs($path);
                 
                    
        //             print_r($usr->getErrors());die;

        //         }else if($ext=='png'){
                    
        //             $path = Yii::$app->params['uploadPath'] .'/png/'. $image->name;
        //             $image->saveAs($path);
                    
        //             print_r($usr->getErrors());die;
        //         }
                
                
        //         return $this->render('entry-confirm', ['msg' => $msg]);

        //     }
    
        // }return $this->render('entry', ['model' => $model]); 
}
                


        //     return $this->render('entry-confirm', []);
        // } else {
        //     // either the page is initially displayed or there is some validation error
        //     return $this->render('entry', ['model' => $model ]);
        // }
    

    public function actionRegister() 
    {
        $model = new RegisterForm();
        $user_model = new Users();
        $user_info_model = new UsersInfo();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // valid data received in $model
            //$count = Users::find()->count();
            //$bl = $model->checkUniqueUsername('aaa');

            $user_model->attributes = \Yii::$app->request->post('RegisterForm');
            //$user_model->user_id = ++$count;
            $user_model->pass = $model->password_hash;
            //$user_model->createdby = $model->user_id;
            $user_model->role_id = $model->role;
            $user_model->save();

            $currentusr = Users::findOne(['username'=>$model->username]);
            $c_id = $currentusr->user_id;
            if(Yii::$app->user->identity){
                $user_to_be_saved = Users::findOne($c_id);
                $user_model->createdby = Yii::$app->user->identity->user_id;
                $user_model->save();
            }else
            {
                $user_to_be_saved = Users::findOne($c_id);
                $user_model->createdby = $c_id;
                $user_model->save();
            }
            $errors=$model->getErrors();

            //$user_info_model = new UsersInfo();
            //$user_info_model->attributes = \Yii::$app->request->post('RegisterForm');
            $user_info_model->user_id = $user_model->user_id;
            $user_info_model->firstname = $model->fname;
            $user_info_model->lastname = $model->lname;
            $user_info_model->save();
            

            return $this->render('register-success', ['model' => $model, 'user_model'=>$user_model,'user_info_model'=>$user_info_model, 'errors'=>$errors ]);
        } else {
            // either the page is initially displayed or there is some validation error
            return $this->render('register', ['model' => $model]);
        }
    }

    public function actionUpdate() 
    {
        $model = new UpdateForm();
        $model->user_id = Yii::$app->user->identity->user_id;
        $model->username = Yii::$app->user->identity->username;
        $model->email = Yii::$app->user->identity->email;
        $model->role = Yii::$app->user->identity->role_id;
        $model->active = Yii::$app->user->identity->active;
        $inf = UsersInfo::findOne($model->user_id);
        $model->fname = $inf->firstname;
        $model->lname = $inf->lastname;


        if ($model->load(Yii::$app->request->post()) && $model->validate()) 
        {
            // valid data received in $model
            $usr = Users::findOne($model->user_id);
            //$usr->user_id = $model->user_id;
            $usr->username = $model->username;
            $usr->pass = $model->password_hash;
            $usr->email = $model->email;
            $usr->role_id = $model->role;
            $usr->active = $model->active;
            $usr->save();

            $usrinf = UsersInfo::findOne($model->user_id);
            $usrinf->firstname = $model->fname;
            $usrinf->lastname = $model->lname;
            $usrinf->save();
            // do something meaningful here about $model ...
            //return $this->redirect(['site/update-success', 'model' => $model]);
            return $this->render('update-success', ['model' => $model]);
        } else {
            // either the page is initially displayed or there is some validation error
            $model->password = '';
            return $this->render('update', ['model' => $model]);
        }
    }

    public function actionSubcat() 
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) 
        {
            $parents = $_POST['depdrop_parents'];

            if ($parents != null) 
            {

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/entry-confirm.php
<?php
use yii\helpers\Html;
?>
<p>Successfully uploaded picture!<?= Html::encode($msg) ?></p>

views/site/entry.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\ArrayHelper;
use \kartik\depdrop\Depdrop;

use app\models\Roles;
use app\models\Users;
use yii\helpers\Url;
use yii\helpers\Json;
?>

<?php 
// $data=array();
//     $data = Users::find()->where([
//         'role_id' => 1
//     ])->select(['user_id as id','username as name'])->asArray()->all();
//     print_r($data[0]);
//     //$result = ArrayHelper::map($data, 'id', 'name');
//     echo '</br>';
//     echo Json::encode($data[0]);
//     echo '</br>';
//     $v = Json::encode($data[0]);
//     $s =  str_replace(':','=>',$v);
//     $g =  str_replace('"','\'',$s);
//     echo $g;
    //print_r(v);
    //print_r($result);
echo Yii::$app->basePath;

?>
<?php $form = ActiveForm::begin([
          'options'=>['enctype'=>'multipart/form-data']]); ?>

   <!-- $form->field($model, 'role')->dropDownList([1=>'admin',2=>'user'],['prompt'=>'Select Role']);  -->

   <?php 
    $roles=Roles::find()->all();
    $list=ArrayHelper::map($roles,'role_id','rolename');
    ?>
<!-- , ['prompt'=>'Select Role']     , ['role_id'=>'rolename']   -->
   <?= $form->field($model, 'role')->dropDownList($list, ['id'=>'roledrop','prompt'=>'Select Role']); ?>

    <?= $form->field($model, 'user_id')->widget(DepDrop::classname(), [
        //'options' => ['multiple' => true,],
        'pluginOptions'=>[
         'depends'=>['roledrop'],
         'placeholder' => 'Select...',
         'url' => Url::to(['/site/subcat']),
         ]
        ]);
    ?>

    <?= $form->field($model, 'image')->widget(FileInput::classname(), [
              'options' => ['accept' => ['image/*','application/pdf'],'multiple' => false],
               'pluginOptions'=>['allowedFileExtensions'=>['jpg','gif','png'],'showUpload' => false,],
          ]);   ?>

    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>
<?php print_r($model->getErrors()); ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php
 $identity = Yii::$app->user->identity;
 $isGuest = Yii::$app->user->isGuest;
 
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= var_dump($identity) ?>
    <?= var_dump($isGuest) ?>
    
    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'pass')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/register-success.php
<?php
use yii\helpers\Html;
?>
<h2>You have successfully created a user!</h2>
<p>You have entered the following information:</p>

<ul>
    <li><label>Username</label>: <?= Html::encode($model->username) ?></li>
    <li><label>Password</label>: <?= Html::encode($model->password_hash) ?></li>
    <li><label>Email</label>: <?= Html::encode($model->email) ?></li>
    <li><label>FirstName</label>: <?= Html::encode($model->fname) ?></li>
    <li><label>LastName</label>: <?= Html::encode($model->lname) ?></li>
    <li><label>Role</label>: <?= Html::encode($model->role) ?></li>
    <li><label>Active</label>: <?= Html::encode($model->active) ?></li>
</ul>
<br>

<?= var_dump($errors) ?>


<!-- <ul>
    <li><label>User ID</label>: <?= Html::encode($user_model->user_id) ?></li>
    <li><label>Username</label>: <?= Html::encode($user_model->username) ?></li>
    <li><label>Password</label>: <?= Html::encode($user_model->pass ) ?></li>
    <li><label>Email</label>: <?= Html::encode($user_model->email) ?></li>
    <li><label>FirstName</label>: <?= Html::encode($user_info_model->firstname) ?></li>
    <li><label>LastName</label>: <?= Html::encode($user_info_model->lastname) ?></li>
    <li><label>Role</label>: <?= Html::encode($user_model->role_id) ?></li>
    <li><label>Created By</label>: <?= Html::encode($user_model->createdby) ?></li>
    <li><label>Active</label>: <?= Html::encode($user_model->active) ?></li>
</ul> -->

views/site/register.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h2>Enter your info!</h2>
<?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'email')->input('email') ?>

    <?= $form->field($model, 'fname') ?>

    <?= $form->field($model, 'lname') ?>

    <?= $form->field($model, 'role')->dropDownList([1=>'admin',2=>'user'],['prompt'=>'Select Role']); ?>

    <?= $form->field($model, 'active')->checkBox(['active' => 'Active']) ?>

    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
  
<?php ActiveForm::end(); ?>

views/site/say.php
<?php
use yii\helpers\Html;
?>
<?= Html::encode($message) ?>

views/site/update-success.php
<?php
use yii\helpers\Html;


?>

<h2>You have successfully updated your info!</h2>
<p>You have entered the following information:</p>

<ul>
    <li><label>Username</label>: <?= Html::encode($model->username) ?></li>
    <li><label>Password</label>: <?= Html::encode($model->password) ?></li>
    <li><label>Email</label>: <?= Html::encode($model->email) ?></li>
    <li><label>FirstName</label>: <?= Html::encode($model->fname) ?></li>
    <li><label>LastName</label>: <?= Html::encode($model->lname) ?></li>
    <li><label>Role</label>: <?= Html::encode($model->role) ?></li>
    <li><label>Active</label>: <?= Html::encode($model->active) ?></li>
</ul>

views/site/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$identity = Yii::$app->user->identity;
 $isGuest = Yii::$app->user->isGuest;
?>
<h2>You can update your info!</h2>
<?= var_dump($identity) ?>
<?= var_dump($isGuest) ?>

<?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'username')->textInput()->input('username') ?>

    <?= $form->field($model, 'password')->passwordInput()->hint('Please enter/or change your password again') ?>

    <?= $form->field($model, 'email')->input('email') ?>

    <?= $form->field($model, 'fname') ?>

    <?= $form->field($model, 'lname') ?>

    <?= $form->field($model, 'role')->dropDownList([1=>'admin',2=>'user'],['prompt'=>'Select Role']); ?>

    <?= $form->field($model, 'active')->checkBox(['active' => 'Active']) ?>

    <div class="form-group">
        <?= Html::submitButton('Update', ['class' => 'btn btn-primary']) ?>
    </div>
  
<?php ActiveForm::end(); ?>